// Language translations
const translations = {
    // English (default)
    en: {
        "nav-about": "About",
        "nav-procedures": "Procedures",
        "nav-gallery": "Before & After",
        "nav-lipedema": "Lipedema",
        "nav-faq": "FAQ",
        "nav-testimonials": "Testimonials",
        "nav-contact": "Contact",
        "nav-tools": "Tools",
        "request-appointment": "Request an Appointment",
        "request-appointment-today": "Request an Appointment Today!",
        "hero-title": "Liposuction in Johnson City, TN",
        "hero-text": "Liposuction is a surgical technique that enhances body contours by removing excess fat deposits located between the skin and muscle. While traditionally used solely for fat reduction, our newer techniques combine traditional liposuction with RF energy devices (like BodyTite) to also tighten the skin and improve body shape. Our focus is on achieving a natural, aesthetically pleasing contour.",
        "procedures-title": "Modern Liposuction Techniques",
        "procedures-subtitle": "Advanced body contouring solutions for your unique needs",
        "procedures-heading": "Combining Traditional Methods with RF Energy",
        "procedures-text-1": "At The Caudle Center, we utilize cutting-edge liposuction techniques that go beyond traditional fat removal. By combining conventional liposuction with radiofrequency (RF) energy devices like BodyTite, we offer superior skin tightening and enhanced body shaping results.",
        "procedures-text-2": "For patients with pre-existing skin laxity, using these combined techniques is essential for optimal outcomes. The RF energy stimulates collagen production, resulting in firmer, more youthful-looking skin in addition to the improved contours from fat removal.",
        "feature-1": "Precise Fat Removal",
        "feature-2": "Enhanced Skin Tightening",
        "feature-3": "Reduced Recovery Time",
        "feature-4": "Natural-Looking Results",
        "tools-title": "Interactive Tools",
        "tools-subtitle": "Plan your procedure with our helpful resources",
        "appointment-tool-title": "Real-Time Appointment Scheduler",
        "appointment-tool-text": "Check our availability and book your consultation instantly.",
        "available-times": "Available Times",
        "confirm-appointment": "Confirm Your Appointment",
        "selected-date": "Selected Date:",
        "selected-time": "Selected Time:",
        "confirm-btn": "Confirm Appointment",
        "appointment-confirmed": "Appointment Confirmed!",
        "appointment-confirmation-text": "We've sent a confirmation email with all the details. We look forward to seeing you!",
        "cost-tool-title": "Procedure Cost Estimator",
        "cost-tool-text": "Get an estimate for your procedure based on your specific needs.",
        "procedure-type": "Procedure Type:",
        "select-procedure": "Select Procedure",
        "traditional-lipo": "Traditional Liposuction",
        "rf-lipo": "Liposuction with RF Energy (BodyTite)",
        "combined-procedures": "Combined Procedures",
        "lipedema-treatment": "Lipedema Treatment",
        "treatment-areas": "Treatment Areas:",
        "select-area": "Select Primary Area",
        "multiple-areas": "Multiple Areas",
        "additional-areas-text": "Select additional areas:",
        "abdomen": "Abdomen",
        "flanks": "Flanks",
        "thighs": "Thighs",
        "arms": "Arms",
        "back": "Back",
        "breast": "Breast",
        "neck": "Neck",
        "fat-volume": "Volume of Fat Removal:",
        "select-volume": "Select Volume",
        "small-volume": "Up to 6 lbs",
        "medium-volume": "6-8 lbs",
        "large-volume": "More than 8 lbs",
        "number-of-sessions": "Number of Sessions:",
        "single-session": "Single Session",
        "two-sessions": "Two Sessions",
        "three-sessions": "Three Sessions",
        "four-sessions": "Four Sessions",
        "additional-treatments": "Additional Treatments:",
        "skin-tightening": "Enhanced Skin Tightening",
        "post-op-care": "Premium Post-Op Care Package",
        "lymphatic-massage": "Lymphatic Massage Sessions",
        "compression-garment": "Custom Compression Garment",
        "calculate-estimate": "Calculate Estimate",
        "estimated-cost": "Estimated Cost",
        "cost-breakdown": "Cost Breakdown",
        "base-procedure": "Base Procedure:",
        "treatment-area-cost": "Treatment Area(s):",
        "volume-cost": "Volume Adjustment:",
        "multiple-sessions": "Multiple Sessions:",
        "addons-cost": "Additional Treatments:",
        "estimated-total": "Estimated Range:",
        "estimate-disclaimer": "Disclaimer: The costs shown are estimates only. Actual prices may vary based on individual consultation, specific needs, and other factors. Please schedule a consultation for an accurate quote.",
        "schedule-consultation": "Schedule Your Consultation",
        "reset-estimate": "Reset Estimate"
    },
    
    // Spanish
    es: {
        "nav-about": "Acerca de",
        "nav-procedures": "Procedimientos",
        "nav-gallery": "Antes y Después",
        "nav-lipedema": "Lipedema",
        "nav-faq": "Preguntas Frecuentes",
        "nav-testimonials": "Testimonios",
        "nav-contact": "Contacto",
        "nav-tools": "Herramientas",
        "request-appointment": "Solicitar una Cita",
        "request-appointment-today": "¡Solicite una Cita Hoy!",
        "hero-title": "Liposucción en Johnson City, TN",
        "hero-text": "La liposucción es una técnica quirúrgica que mejora los contornos corporales al eliminar los depósitos de grasa ubicados entre la piel y el músculo. Aunque tradicionalmente se usaba solo para reducir grasa, nuestras técnicas más nuevas combinan la liposucción tradicional con dispositivos de energía RF (como BodyTite) para tensar la piel y mejorar la forma del cuerpo. Nuestro enfoque es lograr un contorno natural y estéticamente agradable.",
        "procedures-title": "Técnicas Modernas de Liposucción",
        "procedures-subtitle": "Soluciones avanzadas de contorno corporal para sus necesidades únicas",
        "procedures-heading": "Combinando Métodos Tradicionales con Energía RF",
        "procedures-text-1": "En The Caudle Center, utilizamos técnicas de liposucción de vanguardia que van más allá de la eliminación tradicional de grasa. Al combinar la liposucción convencional con dispositivos de radiofrecuencia (RF) como BodyTite, ofrecemos un tensado superior de la piel y resultados mejorados de modelado corporal.",
        "procedures-text-2": "Para pacientes con flacidez preexistente de la piel, el uso de estas técnicas combinadas es esencial para obtener resultados óptimos. La energía RF estimula la producción de colágeno, lo que resulta en una piel más firme y de aspecto más juvenil, además de los contornos mejorados por la eliminación de grasa.",
        "feature-1": "Eliminación Precisa de Grasa",
        "feature-2": "Tensado Mejorado de la Piel",
        "feature-3": "Tiempo de Recuperación Reducido",
        "feature-4": "Resultados de Aspecto Natural",
        "tools-title": "Herramientas Interactivas",
        "tools-subtitle": "Planifique su procedimiento con nuestros recursos útiles",
        "appointment-tool-title": "Programador de Citas en Tiempo Real",
        "appointment-tool-text": "Verifique nuestra disponibilidad y reserve su consulta al instante.",
        "available-times": "Horarios Disponibles",
        "confirm-appointment": "Confirmar Su Cita",
        "selected-date": "Fecha Seleccionada:",
        "selected-time": "Hora Seleccionada:",
        "confirm-btn": "Confirmar Cita",
        "appointment-confirmed": "¡Cita Confirmada!",
        "appointment-confirmation-text": "Hemos enviado un correo electrónico de confirmación con todos los detalles. ¡Esperamos verle pronto!",
        "cost-tool-title": "Estimador de Costos de Procedimientos",
        "cost-tool-text": "Obtenga un estimado para su procedimiento basado en sus necesidades específicas.",
        "procedure-type": "Tipo de Procedimiento:",
        "select-procedure": "Seleccionar Procedimiento",
        "traditional-lipo": "Liposucción Tradicional",
        "rf-lipo": "Liposucción con Energía RF (BodyTite)",
        "combined-procedures": "Procedimientos Combinados",
        "lipedema-treatment": "Tratamiento de Lipedema",
        "treatment-areas": "Áreas de Tratamiento:",
        "select-area": "Seleccionar Área Principal",
        "multiple-areas": "Múltiples Áreas",
        "additional-areas-text": "Seleccionar áreas adicionales:",
        "abdomen": "Abdomen",
        "flanks": "Flancos",
        "thighs": "Muslos",
        "arms": "Brazos",
        "back": "Espalda",
        "breast": "Pecho",
        "neck": "Cuello",
        "fat-volume": "Volumen de Grasa a Eliminar:",
        "select-volume": "Seleccionar Volumen",
        "small-volume": "Hasta 6 libras",
        "medium-volume": "6-8 libras",
        "large-volume": "Más de 8 libras",
        "number-of-sessions": "Número de Sesiones:",
        "single-session": "Sesión Única",
        "two-sessions": "Dos Sesiones",
        "three-sessions": "Tres Sesiones",
        "four-sessions": "Cuatro Sesiones",
        "additional-treatments": "Tratamientos Adicionales:",
        "skin-tightening": "Tensado de Piel Mejorado",
        "post-op-care": "Paquete Premium de Cuidado Postoperatorio",
        "lymphatic-massage": "Sesiones de Masaje Linfático",
        "compression-garment": "Prenda de Compresión Personalizada",
        "calculate-estimate": "Calcular Estimado",
        "estimated-cost": "Costo Estimado",
        "cost-breakdown": "Desglose de Costos",
        "base-procedure": "Procedimiento Base:",
        "treatment-area-cost": "Área(s) de Tratamiento:",
        "volume-cost": "Ajuste de Volumen:",
        "multiple-sessions": "Sesiones Múltiples:",
        "addons-cost": "Tratamientos Adicionales:",
        "estimated-total": "Rango Estimado:",
        "estimate-disclaimer": "Aviso: Los costos mostrados son solo estimaciones. Los precios reales pueden variar según la consulta individual, necesidades específicas y otros factores. Por favor, programe una consulta para obtener un presupuesto preciso.",
        "schedule-consultation": "Programar Su Consulta",
        "reset-estimate": "Reiniciar Estimado"
    },
    
    // French
    fr: {
        "nav-about": "À Propos",
        "nav-procedures": "Procédures",
        "nav-gallery": "Avant et Après",
        "nav-lipedema": "Lipœdème",
        "nav-faq": "FAQ",
        "nav-testimonials": "Témoignages",
        "nav-contact": "Contact",
        "nav-tools": "Outils",
        "request-appointment": "Demander un Rendez-vous",
        "request-appointment-today": "Demandez un Rendez-vous Aujourd'hui !",
        "hero-title": "Liposuccion à Johnson City, TN",
        "hero-text": "La liposuccion est une technique chirurgicale qui améliore les contours du corps en éliminant les dépôts de graisse situés entre la peau et le muscle. Bien que traditionnellement utilisée uniquement pour la réduction de graisse, nos nouvelles techniques combinent la liposuccion traditionnelle avec des appareils à énergie RF (comme BodyTite) pour également raffermir la peau et améliorer la forme du corps. Notre objectif est d'obtenir un contour naturel et esthétiquement agréable.",
        "procedures-title": "Techniques Modernes de Liposuccion",
        "procedures-subtitle": "Solutions avancées de remodelage corporel pour vos besoins uniques",
        "procedures-heading": "Combinaison des Méthodes Traditionnelles avec l'Énergie RF",
        "procedures-text-1": "Au Centre Caudle, nous utilisons des techniques de liposuccion de pointe qui vont au-delà de l'élimination traditionnelle des graisses. En combinant la liposuccion conventionnelle avec des appareils à radiofréquence (RF) comme BodyTite, nous offrons un raffermissement supérieur de la peau et des résultats améliorés de remodelage corporel.",
        "procedures-text-2": "Pour les patients présentant un relâchement cutané préexistant, l'utilisation de ces techniques combinées est essentielle pour des résultats optimaux. L'énergie RF stimule la production de collagène, ce qui donne une peau plus ferme et d'apparence plus jeune, en plus des contours améliorés par l'élimination des graisses.",
        "feature-1": "Élimination Précise des Graisses",
        "feature-2": "Raffermissement Amélioré de la Peau",
        "feature-3": "Temps de Récupération Réduit",
        "feature-4": "Résultats d'Apparence Naturelle",
        "tools-title": "Outils Interactifs",
        "tools-subtitle": "Planifiez votre procédure avec nos ressources utiles",
        "appointment-tool-title": "Planificateur de Rendez-vous en Temps Réel",
        "appointment-tool-text": "Vérifiez notre disponibilité et réservez votre consultation instantanément.",
        "available-times": "Horaires Disponibles",
        "confirm-appointment": "Confirmer Votre Rendez-vous",
        "selected-date": "Date Sélectionnée :",
        "selected-time": "Heure Sélectionnée :",
        "confirm-btn": "Confirmer le Rendez-vous",
        "appointment-confirmed": "Rendez-vous Confirmé !",
        "appointment-confirmation-text": "Nous avons envoyé un e-mail de confirmation avec tous les détails. Nous avons hâte de vous voir !",
        "cost-tool-title": "Estimateur de Coût de Procédure",
        "cost-tool-text": "Obtenez une estimation pour votre procédure basée sur vos besoins spécifiques.",
        "procedure-type": "Type de Procédure :",
        "select-procedure": "Sélectionner une Procédure",
        "traditional-lipo": "Liposuccion Traditionnelle",
        "rf-lipo": "Liposuccion avec Énergie RF (BodyTite)",
        "combined-procedures": "Procédures Combinées",
        "lipedema-treatment": "Traitement du Lipœdème",
        "treatment-areas": "Zones de Traitement :",
        "select-area": "Sélectionner la Zone Principale",
        "multiple-areas": "Zones Multiples",
        "additional-areas-text": "Sélectionner des zones supplémentaires :",
        "abdomen": "Abdomen",
        "flanks": "Flancs",
        "thighs": "Cuisses",
        "arms": "Bras",
        "back": "Dos",
        "breast": "Poitrine",
        "neck": "Cou",
        "fat-volume": "Volume de Graisse à Éliminer :",
        "select-volume": "Sélectionner le Volume",
        "small-volume": "Jusqu'à 2,7 kg",
        "medium-volume": "2,7-3,6 kg",
        "large-volume": "Plus de 3,6 kg",
        "number-of-sessions": "Nombre de Séances :",
        "single-session": "Séance Unique",
        "two-sessions": "Deux Séances",
        "three-sessions": "Trois Séances",
        "four-sessions": "Quatre Séances",
        "additional-treatments": "Traitements Supplémentaires :",
        "skin-tightening": "Raffermissement Cutané Amélioré",
        "post-op-care": "Forfait Premium de Soins Post-opératoires",
        "lymphatic-massage": "Séances de Drainage Lymphatique",
        "compression-garment": "Vêtement de Compression Personnalisé",
        "calculate-estimate": "Calculer l'Estimation",
        "estimated-cost": "Coût Estimé",
        "cost-breakdown": "Détail des Coûts",
        "base-procedure": "Procédure de Base :",
        "treatment-area-cost": "Zone(s) de Traitement :",
        "volume-cost": "Ajustement du Volume :",
        "multiple-sessions": "Sessions Multiples :",
        "addons-cost": "Traitements Supplémentaires :",
        "estimated-total": "Fourchette Estimée :",
        "estimate-disclaimer": "Avertissement : Les coûts indiqués ne sont que des estimations. Les prix réels peuvent varier en fonction de la consultation individuelle, des besoins spécifiques et d'autres facteurs. Veuillez prendre rendez-vous pour une consultation afin d'obtenir un devis précis.",
        "schedule-consultation": "Planifier Votre Consultation",
        "reset-estimate": "Réinitialiser l'Estimation"
    },
    
    // Chinese
    zh: {
        "nav-about": "关于我们",
        "nav-procedures": "手术项目",
        "nav-gallery": "前后对比",
        "nav-lipedema": "脂肪瘤",
        "nav-faq": "常见问题",
        "nav-testimonials": "客户评价",
        "nav-contact": "联系我们",
        "nav-tools": "工具",
        "request-appointment": "预约咨询",
        "request-appointment-today": "立即预约咨询！",
        "hero-title": "田纳西州约翰逊市的吸脂手术",
        "hero-text": "吸脂是一种通过去除皮肤和肌肉之间多余脂肪沉积来改善身体轮廓的外科技术。虽然传统上仅用于减少脂肪，但我们的新技术将传统吸脂与射频能量设备（如BodyTite）相结合，还可以紧致皮肤并改善身体形态。我们的重点是实现自然、美观的轮廓。",
        "procedures-title": "现代吸脂技术",
        "procedures-subtitle": "为您的独特需求提供先进的身体塑形解决方案",
        "procedures-heading": "结合传统方法与射频能量",
        "procedures-text-1": "在考德尔中心，我们使用的尖端吸脂技术超越了传统的脂肪去除。通过将传统吸脂与射频（RF）能量设备（如BodyTite）相结合，我们提供卓越的皮肤紧致和增强的身体塑形效果。",
        "procedures-text-2": "对于已有皮肤松弛的患者，使用这些组合技术对于获得最佳效果至关重要。射频能量刺激胶原蛋白生成，除了通过脂肪去除改善轮廓外，还能使皮肤更紧致、更年轻。",
        "feature-1": "精确脂肪去除",
        "feature-2": "增强皮肤紧致",
        "feature-3": "缩短恢复时间",
        "feature-4": "自然外观效果",
        "tools-title": "互动工具",
        "tools-subtitle": "使用我们的实用资源规划您的手术",
        "appointment-tool-title": "实时预约安排",
        "appointment-tool-text": "查看我们的可用时间并立即预约咨询。",
        "available-times": "可用时间",
        "confirm-appointment": "确认您的预约",
        "selected-date": "已选日期：",
        "selected-time": "已选时间：",
        "confirm-btn": "确认预约",
        "appointment-confirmed": "预约已确认！",
        "appointment-confirmation-text": "我们已发送包含所有详细信息的确认电子邮件。期待见到您！",
        "cost-tool-title": "手术费用估算器",
        "cost-tool-text": "根据您的具体需求获取手术费用估算。",
        "procedure-type": "手术类型：",
        "select-procedure": "选择手术",
        "traditional-lipo": "传统吸脂",
        "rf-lipo": "射频能量吸脂 (BodyTite)",
        "combined-procedures": "组合手术",
        "lipedema-treatment": "脂肪瘤治疗",
        "treatment-areas": "治疗区域：",
        "select-area": "选择主要区域",
        "multiple-areas": "多个区域",
        "additional-areas-text": "选择额外区域：",
        "abdomen": "腹部",
        "flanks": "侧腰",
        "thighs": "大腿",
        "arms": "手臂",
        "back": "背部",
        "breast": "胸部",
        "neck": "颈部",
        "fat-volume": "脂肪去除量：",
        "select-volume": "选择体积",
        "small-volume": "最多6磅",
        "medium-volume": "6-8磅",
        "large-volume": "超过8磅",
        "number-of-sessions": "疗程数量：",
        "single-session": "单次疗程",
        "two-sessions": "两次疗程",
        "three-sessions": "三次疗程",
        "four-sessions": "四次疗程",
        "additional-treatments": "额外治疗：",
        "skin-tightening": "强化皮肤紧致",
        "post-op-care": "高级术后护理套餐",
        "lymphatic-massage": "淋巴按摩疗程",
        "compression-garment": "定制压力衣",
        "calculate-estimate": "计算估算",
        "estimated-cost": "估算费用",
        "cost-breakdown": "费用明细",
        "base-procedure": "基础手术：",
        "treatment-area-cost": "治疗区域：",
        "volume-cost": "体积调整：",
        "multiple-sessions": "多次疗程：",
        "addons-cost": "额外治疗：",
        "estimated-total": "估算范围：",
        "estimate-disclaimer": "免责声明：显示的费用仅为估算。实际价格可能因个人咨询、具体需求和其他因素而有所不同。请预约咨询以获取准确报价。",
        "schedule-consultation": "预约咨询",
        "reset-estimate": "重置估算"
    }
};

// Initialize language functionality
document.addEventListener('DOMContentLoaded', function() {
    // Set default language
    let currentLang = 'en';
    
    // Get language buttons
    const langButtons = document.querySelectorAll('.language-btn');
    
    // Add click event to language buttons
    langButtons.forEach(button => {
        button.addEventListener('click', function() {
            // Get language code
            const lang = this.getAttribute('data-lang');
            
            // Update active button
            langButtons.forEach(btn => btn.classList.remove('active'));
            this.classList.add('active');
            
            // Change language
            changeLanguage(lang);
        });
    });
    
    // Function to change language
    function changeLanguage(lang) {
        // Update current language
        currentLang = lang;
        
        // Get all elements with data-lang-key attribute
        const elements = document.querySelectorAll('[data-lang-key]');
        
        // Update text for each element
        elements.forEach(element => {
            const key = element.getAttribute('data-lang-key');
            
            // Check if translation exists
            if (translations[lang] && translations[lang][key]) {
                // Check element type
                if (element.tagName === 'INPUT' || element.tagName === 'TEXTAREA') {
                    // For input elements, update placeholder
                    element.placeholder = translations[lang][key];
                } else if (element.tagName === 'OPTION') {
                    // For option elements, update text
                    element.textContent = translations[lang][key];
                } else {
                    // For other elements, update inner text
                    element.textContent = translations[lang][key];
                }
            }
        });
        
        // Update document language
        document.documentElement.lang = lang;
    }
}); 